<a href="https://colab.research.google.com/github/sunshineluyao/ESG_with_benchmark/blob/main/Categorization/ESG_Categorization_Jul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### import packages
import pandas as pd
import numpy as np
### show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
### Import data
df_Jul= pd.read_csv("https://raw.githubusercontent.com/sunshineluyao/ESG_with_benchmark/main/rawdata/SP1500_Jul.csv")
df_Jul.head()

,Symbol,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,30 MktVal Co,30 Closing Price,31 MktVal Co,31 Closing Price,STD MktVal,STD Closing Price
0,A,"Agilent Technologies, Inc.",NYSE,Healthcare,"27,286.7",0.5,309.7,"26,461.7",0.0,17.5,9.3,"5,223.0",10.0,5.5,6.6,AAA,"27,206.4",88.1,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,576.9",89.3,"27,546.0",89.2,"27,647.9",89.5,"27,765.3",89.9,"27,610.9",89.4,"27,610.9",89.4,"27,610.9",89.4,"27,561.5",89.3,"28,003.0",90.7,"28,679.2",92.9,"28,673.1",92.9,"29,139.3",94.4,"29,139.3",94.4,"29,139.3",94.4,"29,398.7",95.2,"29,648.8",96.0,"29,750.7",96.4,"29,846.4",96.7,"29,275.2",94.8,"29,275.2",94.8,"29,275.2",94.8,"30,034.8",97.3,"29,426.5",95.3,"29,982.3",97.1,"29,621.0",95.9,"29,744.5",96.3,997.5,3.2
1,AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"6,641.0",-14.7,428.2,"12,280.8",-0.5,-59.3,-13.2,"33,361.0",3.3,5.1,2.5,CCC,"6,508.9",12.8,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,503.8",12.8,"6,051.6",11.9,"6,092.2",12.0,"5,680.7",11.2,"6,066.8",11.9,"6,066.8",11.9,"6,066.8",11.9,"5,909.3",11.6,"5,878.8",11.6,"6,829.0",13.4,"6,326.0",12.5,"6,051.6",11.9,"6,051.6",11.9,"6,051.6",11.9,"5,828.0",11.5,"5,828.0",11.5,"5,772.1",11.4,"5,985.8",11.8,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,985.8",11.8,"5,797.6",11.4,"5,685.7",11.2,"5,655.2",11.1,285.7,0.6
2,AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,067.7",12.1,66.7,"3,835.1",0.2,-27.6,15.2,"4,098.8",3.4,6.0,4.8,A,"3,060.3",45.3,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,043.4",45.0,"2,936.0",43.5,"2,961.0",43.8,"2,960.3",43.8,"2,979.9",44.1,"2,979.9",44.1,"2,979.9",44.1,"2,865.7",42.4,"2,894.1",42.8,"3,034.0",44.9,"2,975.9",44.0,"2,915.0",43.1,"2,915.0",43.1,"2,915.0",43.1,"2,879.2",42.6,"2,952.2",43.7,"2,983.1",44.4,"3,017.3",44.9,"3,001.2",44.7,"3,001.2",44.7,"3,001.2",44.7,"3,086.5",46.0,"3,032.7",45.2,"3,651.8",54.4,"3,542.3",52.8,"3,503.4",52.2,184.7,2.8
3,AAOI,"Applied Optoelectronics, Inc.",NASDAQ,Technology,221.1,13.4,20.1,239.0,1.1,6.8,39.5,200.4,NaN,NaN,NaN,@NA,207.3,10.2,219.5,10.8,219.5,10.8,219.5,10.8,219.5,10.8,235.5,11.6,226.8,11.2,229.6,11.3,244.1,12.0,234.1,11.5,234.1,11.5,234.1,11.5,219.7,10.8,217.8,10.7,226.2,11.1,216.9,10.7,228.6,11.2,228.6,11.2,228.6,11.2,244.4,12.0,283.2,13.9,292.7,14.4,289.4,14.2,277.0,13.6,277.0,13.6,277.0,13.6,284.1,14.0,269.3,13.2,275.2,13.5,282.1,13.9,323.6,14.2,30.3,1.4
4,AAON,"AAON, Inc.",NASDAQ,Industrials,"2,824.8",5.5,52.1,"2,574.2",0.1,9.9,12.5,499.2,5.5,7.0,8.4,A,"2,741.5",52.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,840.4",54.6,"2,872.7",55.2,"2,823.8",54.3,"2,780.6",53.4,"2,819.1",54.2,"2,819.1",54.2,"2,819.1",54.2,"2,834.2",54.5,"2,926.3",56.2,"3,000.1",57.7,"2,999.1",57.6,"3,023.0",58.1,"3,023.0",58.1,"3,023.0",58.1,"2,992.3",57.5,"3,012.6",57.9,"3,023.6",58.1,"3,043.3",58.5,"2,999.1",57.6,"2,999.1",57.6,"2,999.1",57.6,"3,013.7",57.9,"2,967.9",57.0,"3,075.1",59.1,"3,030.3",58.2,"3,082.9",59.3,107.1,2.1

In [3]:
df_Jul=df_Jul.dropna()

In [4]:
df_Jul=df_Jul.set_index('Symbol',drop=True)
df_Jul.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,30 MktVal Co,30 Closing Price,31 MktVal Co,31 Closing Price,STD MktVal,STD Closing Price
Symbol,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
A,"Agilent Technologies, Inc.",NYSE,Healthcare,"27,286.7",0.5,309.7,"26,461.7",0.0,17.5,9.3,"5,223.0",10.0,5.5,6.6,AAA,"27,206.4",88.1,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,576.9",89.3,"27,546.0",89.2,"27,647.9",89.5,"27,765.3",89.9,"27,610.9",89.4,"27,610.9",89.4,"27,610.9",89.4,"27,561.5",89.3,"28,003.0",90.7,"28,679.2",92.9,"28,673.1",92.9,"29,139.3",94.4,"29,139.3",94.4,"29,139.3",94.4,"29,398.7",95.2,"29,648.8",96.0,"29,750.7",96.4,"29,846.4",96.7,"29,275.2",94.8,"29,275.2",94.8,"29,275.2",94.8,"30,034.8",97.3,"29,426.5",95.3,"29,982.3",97.1,"29,621.0",95.9,"29,744.5",96.3,997.5,3.2
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"6,641.0",-14.7,428.2,"12,280.8",-0.5,-59.3,-13.2,"33,361.0",3.3,5.1,2.5,CCC,"6,508.9",12.8,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,503.8",12.8,"6,051.6",11.9,"6,092.2",12.0,"5,680.7",11.2,"6,066.8",11.9,"6,066.8",11.9,"6,066.8",11.9,"5,909.3",11.6,"5,878.8",11.6,"6,829.0",13.4,"6,326.0",12.5,"6,051.6",11.9,"6,051.6",11.9,"6,051.6",11.9,"5,828.0",11.5,"5,828.0",11.5,"5,772.1",11.4,"5,985.8",11.8,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,985.8",11.8,"5,797.6",11.4,"5,685.7",11.2,"5,655.2",11.1,285.7,0.6
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,067.7",12.1,66.7,"3,835.1",0.2,-27.6,15.2,"4,098.8",3.4,6.0,4.8,A,"3,060.3",45.3,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,043.4",45.0,"2,936.0",43.5,"2,961.0",43.8,"2,960.3",43.8,"2,979.9",44.1,"2,979.9",44.1,"2,979.9",44.1,"2,865.7",42.4,"2,894.1",42.8,"3,034.0",44.9,"2,975.9",44.0,"2,915.0",43.1,"2,915.0",43.1,"2,915.0",43.1,"2,879.2",42.6,"2,952.2",43.7,"2,983.1",44.4,"3,017.3",44.9,"3,001.2",44.7,"3,001.2",44.7,"3,001.2",44.7,"3,086.5",46.0,"3,032.7",45.2,"3,651.8",54.4,"3,542.3",52.8,"3,503.4",52.2,184.7,2.8
AAON,"AAON, Inc.",NASDAQ,Industrials,"2,824.8",5.5,52.1,"2,574.2",0.1,9.9,12.5,499.2,5.5,7.0,8.4,A,"2,741.5",52.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,840.4",54.6,"2,872.7",55.2,"2,823.8",54.3,"2,780.6",53.4,"2,819.1",54.2,"2,819.1",54.2,"2,819.1",54.2,"2,834.2",54.5,"2,926.3",56.2,"3,000.1",57.7,"2,999.1",57.6,"3,023.0",58.1,"3,023.0",58.1,"3,023.0",58.1,"2,992.3",57.5,"3,012.6",57.9,"3,023.6",58.1,"3,043.3",58.5,"2,999.1",57.6,"2,999.1",57.6,"2,999.1",57.6,"3,013.7",57.9,"2,967.9",57.0,"3,075.1",59.1,"3,030.3",58.2,"3,082.9",59.3,107.1,2.1
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,"9,843.5",26.7,69.2,"11,092.6",0.2,-8.6,5.8,"9,624.0",2.0,5.9,4.6,BBB,"9,808.9",142.0,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,602.3",139.0,"9,444.8",136.7,"9,428.9",136.5,"9,242.3",133.8,"9,290.7",134.5,"9,290.7",134.5,"9,290.7",134.5,"9,337.6",135.1,"9,576.0",138.6,"9,928.5",143.7,"10,043.9",145.4,"10,010.0",144.9,"10,010.0",144.9,"10,010.0",144.9,"10,012.8",144.9,"10,184.1",147.4,"10,323.7",149.4,"10,252.6",148.4,"10,176.5",147.3,"10,176.5",147.3,"10,176.5",147.3,"10,146.1",146.8,"10,101.9",146.2,"10,241.5",148.2,"10,563.5",152.9,"10,374.9",150.1,369.1,5.3

In [5]:
df_Jul.index.name=None
df_Jul.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,30 MktVal Co,30 Closing Price,31 MktVal Co,31 Closing Price,STD MktVal,STD Closing Price
A,"Agilent Technologies, Inc.",NYSE,Healthcare,"27,286.7",0.5,309.7,"26,461.7",0.0,17.5,9.3,"5,223.0",10.0,5.5,6.6,AAA,"27,206.4",88.1,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,576.9",89.3,"27,546.0",89.2,"27,647.9",89.5,"27,765.3",89.9,"27,610.9",89.4,"27,610.9",89.4,"27,610.9",89.4,"27,561.5",89.3,"28,003.0",90.7,"28,679.2",92.9,"28,673.1",92.9,"29,139.3",94.4,"29,139.3",94.4,"29,139.3",94.4,"29,398.7",95.2,"29,648.8",96.0,"29,750.7",96.4,"29,846.4",96.7,"29,275.2",94.8,"29,275.2",94.8,"29,275.2",94.8,"30,034.8",97.3,"29,426.5",95.3,"29,982.3",97.1,"29,621.0",95.9,"29,744.5",96.3,997.5,3.2
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"6,641.0",-14.7,428.2,"12,280.8",-0.5,-59.3,-13.2,"33,361.0",3.3,5.1,2.5,CCC,"6,508.9",12.8,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,503.8",12.8,"6,051.6",11.9,"6,092.2",12.0,"5,680.7",11.2,"6,066.8",11.9,"6,066.8",11.9,"6,066.8",11.9,"5,909.3",11.6,"5,878.8",11.6,"6,829.0",13.4,"6,326.0",12.5,"6,051.6",11.9,"6,051.6",11.9,"6,051.6",11.9,"5,828.0",11.5,"5,828.0",11.5,"5,772.1",11.4,"5,985.8",11.8,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,985.8",11.8,"5,797.6",11.4,"5,685.7",11.2,"5,655.2",11.1,285.7,0.6
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,067.7",12.1,66.7,"3,835.1",0.2,-27.6,15.2,"4,098.8",3.4,6.0,4.8,A,"3,060.3",45.3,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,043.4",45.0,"2,936.0",43.5,"2,961.0",43.8,"2,960.3",43.8,"2,979.9",44.1,"2,979.9",44.1,"2,979.9",44.1,"2,865.7",42.4,"2,894.1",42.8,"3,034.0",44.9,"2,975.9",44.0,"2,915.0",43.1,"2,915.0",43.1,"2,915.0",43.1,"2,879.2",42.6,"2,952.2",43.7,"2,983.1",44.4,"3,017.3",44.9,"3,001.2",44.7,"3,001.2",44.7,"3,001.2",44.7,"3,086.5",46.0,"3,032.7",45.2,"3,651.8",54.4,"3,542.3",52.8,"3,503.4",52.2,184.7,2.8
AAON,"AAON, Inc.",NASDAQ,Industrials,"2,824.8",5.5,52.1,"2,574.2",0.1,9.9,12.5,499.2,5.5,7.0,8.4,A,"2,741.5",52.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,840.4",54.6,"2,872.7",55.2,"2,823.8",54.3,"2,780.6",53.4,"2,819.1",54.2,"2,819.1",54.2,"2,819.1",54.2,"2,834.2",54.5,"2,926.3",56.2,"3,000.1",57.7,"2,999.1",57.6,"3,023.0",58.1,"3,023.0",58.1,"3,023.0",58.1,"2,992.3",57.5,"3,012.6",57.9,"3,023.6",58.1,"3,043.3",58.5,"2,999.1",57.6,"2,999.1",57.6,"2,999.1",57.6,"3,013.7",57.9,"2,967.9",57.0,"3,075.1",59.1,"3,030.3",58.2,"3,082.9",59.3,107.1,2.1
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,"9,843.5",26.7,69.2,"11,092.6",0.2,-8.6,5.8,"9,624.0",2.0,5.9,4.6,BBB,"9,808.9",142.0,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,602.3",139.0,"9,444.8",136.7,"9,428.9",136.5,"9,242.3",133.8,"9,290.7",134.5,"9,290.7",134.5,"9,290.7",134.5,"9,337.6",135.1,"9,576.0",138.6,"9,928.5",143.7,"10,043.9",145.4,"10,010.0",144.9,"10,010.0",144.9,"10,010.0",144.9,"10,012.8",144.9,"10,184.1",147.4,"10,323.7",149.4,"10,252.6",148.4,"10,176.5",147.3,"10,176.5",147.3,"10,176.5",147.3,"10,146.1",146.8,"10,101.9",146.2,"10,241.5",148.2,"10,563.5",152.9,"10,374.9",150.1,369.1,5.3

In [6]:
### formating data so that it can be calculated
df_Jul[['Size','Common Shares Outstdg','MktVal Co']]=df_Jul[['Size','Common Shares Outstdg','MktVal Co']].apply(lambda x: x.str.replace(',', ''), axis=1)
df_Jul.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,30 MktVal Co,30 Closing Price,31 MktVal Co,31 Closing Price,STD MktVal,STD Closing Price
A,"Agilent Technologies, Inc.",NYSE,Healthcare,27286.7,0.5,309.7,26461.7,0.0,17.5,9.3,"5,223.0",10.0,5.5,6.6,AAA,"27,206.4",88.1,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,576.9",89.3,"27,546.0",89.2,"27,647.9",89.5,"27,765.3",89.9,"27,610.9",89.4,"27,610.9",89.4,"27,610.9",89.4,"27,561.5",89.3,"28,003.0",90.7,"28,679.2",92.9,"28,673.1",92.9,"29,139.3",94.4,"29,139.3",94.4,"29,139.3",94.4,"29,398.7",95.2,"29,648.8",96.0,"29,750.7",96.4,"29,846.4",96.7,"29,275.2",94.8,"29,275.2",94.8,"29,275.2",94.8,"30,034.8",97.3,"29,426.5",95.3,"29,982.3",97.1,"29,621.0",95.9,"29,744.5",96.3,997.5,3.2
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,6641.0,-14.7,428.2,12280.8,-0.5,-59.3,-13.2,"33,361.0",3.3,5.1,2.5,CCC,"6,508.9",12.8,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,503.8",12.8,"6,051.6",11.9,"6,092.2",12.0,"5,680.7",11.2,"6,066.8",11.9,"6,066.8",11.9,"6,066.8",11.9,"5,909.3",11.6,"5,878.8",11.6,"6,829.0",13.4,"6,326.0",12.5,"6,051.6",11.9,"6,051.6",11.9,"6,051.6",11.9,"5,828.0",11.5,"5,828.0",11.5,"5,772.1",11.4,"5,985.8",11.8,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,985.8",11.8,"5,797.6",11.4,"5,685.7",11.2,"5,655.2",11.1,285.7,0.6
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3067.7,12.1,66.7,3835.1,0.2,-27.6,15.2,"4,098.8",3.4,6.0,4.8,A,"3,060.3",45.3,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,043.4",45.0,"2,936.0",43.5,"2,961.0",43.8,"2,960.3",43.8,"2,979.9",44.1,"2,979.9",44.1,"2,979.9",44.1,"2,865.7",42.4,"2,894.1",42.8,"3,034.0",44.9,"2,975.9",44.0,"2,915.0",43.1,"2,915.0",43.1,"2,915.0",43.1,"2,879.2",42.6,"2,952.2",43.7,"2,983.1",44.4,"3,017.3",44.9,"3,001.2",44.7,"3,001.2",44.7,"3,001.2",44.7,"3,086.5",46.0,"3,032.7",45.2,"3,651.8",54.4,"3,542.3",52.8,"3,503.4",52.2,184.7,2.8
AAON,"AAON, Inc.",NASDAQ,Industrials,2824.8,5.5,52.1,2574.2,0.1,9.9,12.5,499.2,5.5,7.0,8.4,A,"2,741.5",52.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,840.4",54.6,"2,872.7",55.2,"2,823.8",54.3,"2,780.6",53.4,"2,819.1",54.2,"2,819.1",54.2,"2,819.1",54.2,"2,834.2",54.5,"2,926.3",56.2,"3,000.1",57.7,"2,999.1",57.6,"3,023.0",58.1,"3,023.0",58.1,"3,023.0",58.1,"2,992.3",57.5,"3,012.6",57.9,"3,023.6",58.1,"3,043.3",58.5,"2,999.1",57.6,"2,999.1",57.6,"2,999.1",57.6,"3,013.7",57.9,"2,967.9",57.0,"3,075.1",59.1,"3,030.3",58.2,"3,082.9",59.3,107.1,2.1
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9843.5,26.7,69.2,11092.6,0.2,-8.6,5.8,"9,624.0",2.0,5.9,4.6,BBB,"9,808.9",142.0,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,602.3",139.0,"9,444.8",136.7,"9,428.9",136.5,"9,242.3",133.8,"9,290.7",134.5,"9,290.7",134.5,"9,290.7",134.5,"9,337.6",135.1,"9,576.0",138.6,"9,928.5",143.7,"10,043.9",145.4,"10,010.0",144.9,"10,010.0",144.9,"10,010.0",144.9,"10,012.8",144.9,"10,184.1",147.4,"10,323.7",149.4,"10,252.6",148.4,"10,176.5",147.3,"10,176.5",147.3,"10,176.5",147.3,"10,146.1",146.8,"10,101.9",146.2,"10,241.5",148.2,"10,563.5",152.9,"10,374.9",150.1,369.1,5.3

In [7]:
Conds=[
       df_Jul['MSCI ESG Rtg Overall Company Rating'].isin(['AAA','AA']),
       df_Jul['MSCI ESG Rtg Overall Company Rating'].isin(['CCC','B']),
       df_Jul['MSCI ESG Rtg Overall Company Rating'].isin(['BB','BBB','A'])
]
Choices = [
           'Leader',
           'Laggard',
           'Average'
]
df_Jul['ESG_Index'] =np.select(Conds, Choices)
df_Jul.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,30 MktVal Co,30 Closing Price,31 MktVal Co,31 Closing Price,STD MktVal,STD Closing Price,ESG_Index
A,"Agilent Technologies, Inc.",NYSE,Healthcare,27286.7,0.5,309.7,26461.7,0.0,17.5,9.3,"5,223.0",10.0,5.5,6.6,AAA,"27,206.4",88.1,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,576.9",89.3,"27,546.0",89.2,"27,647.9",89.5,"27,765.3",89.9,"27,610.9",89.4,"27,610.9",89.4,"27,610.9",89.4,"27,561.5",89.3,"28,003.0",90.7,"28,679.2",92.9,"28,673.1",92.9,"29,139.3",94.4,"29,139.3",94.4,"29,139.3",94.4,"29,398.7",95.2,"29,648.8",96.0,"29,750.7",96.4,"29,846.4",96.7,"29,275.2",94.8,"29,275.2",94.8,"29,275.2",94.8,"30,034.8",97.3,"29,426.5",95.3,"29,982.3",97.1,"29,621.0",95.9,"29,744.5",96.3,997.5,3.2,Leader
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,6641.0,-14.7,428.2,12280.8,-0.5,-59.3,-13.2,"33,361.0",3.3,5.1,2.5,CCC,"6,508.9",12.8,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,503.8",12.8,"6,051.6",11.9,"6,092.2",12.0,"5,680.7",11.2,"6,066.8",11.9,"6,066.8",11.9,"6,066.8",11.9,"5,909.3",11.6,"5,878.8",11.6,"6,829.0",13.4,"6,326.0",12.5,"6,051.6",11.9,"6,051.6",11.9,"6,051.6",11.9,"5,828.0",11.5,"5,828.0",11.5,"5,772.1",11.4,"5,985.8",11.8,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,985.8",11.8,"5,797.6",11.4,"5,685.7",11.2,"5,655.2",11.1,285.7,0.6,Laggard
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3067.7,12.1,66.7,3835.1,0.2,-27.6,15.2,"4,098.8",3.4,6.0,4.8,A,"3,060.3",45.3,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,043.4",45.0,"2,936.0",43.5,"2,961.0",43.8,"2,960.3",43.8,"2,979.9",44.1,"2,979.9",44.1,"2,979.9",44.1,"2,865.7",42.4,"2,894.1",42.8,"3,034.0",44.9,"2,975.9",44.0,"2,915.0",43.1,"2,915.0",43.1,"2,915.0",43.1,"2,879.2",42.6,"2,952.2",43.7,"2,983.1",44.4,"3,017.3",44.9,"3,001.2",44.7,"3,001.2",44.7,"3,001.2",44.7,"3,086.5",46.0,"3,032.7",45.2,"3,651.8",54.4,"3,542.3",52.8,"3,503.4",52.2,184.7,2.8,Average
AAON,"AAON, Inc.",NASDAQ,Industrials,2824.8,5.5,52.1,2574.2,0.1,9.9,12.5,499.2,5.5,7.0,8.4,A,"2,741.5",52.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,840.4",54.6,"2,872.7",55.2,"2,823.8",54.3,"2,780.6",53.4,"2,819.1",54.2,"2,819.1",54.2,"2,819.1",54.2,"2,834.2",54.5,"2,926.3",56.2,"3,000.1",57.7,"2,999.1",57.6,"3,023.0",58.1,"3,023.0",58.1,"3,023.0",58.1,"2,992.3",57.5,"3,012.6",57.9,"3,023.6",58.1,"3,043.3",58.5,"2,999.1",57.6,"2,999.1",57.6,"2,999.1",57.6,"3,013.7",57.9,"2,967.9",57.0,"3,075.1",59.1,"3,030.3",58.2,"3,082.9",59.3,107.1,2.1,Average
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9843.5,26.7,69.2,11092.6,0.2,-8.6,5.8,"9,624.0",2.0,5.9,4.6,BBB,"9,808.9",142.0,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,602.3",139.0,"9,444.8",136.7,"9,428.9",136.5,"9,242.3",133.8,"9,290.7",134.5,"9,290.7",134.5,"9,290.7",134.5,"9,337.6",135.1,"9,576.0",138.6,"9,928.5",143.7,"10,043.9",145.4,"10,010.0",144.9,"10,010.0",144.9,"10,010.0",144.9,"10,012.8",144.9,"10,184.1",147.4,"10,323.7",149.4,"10,252.6",148.4,"10,176.5",147.3,"10,176.5",147.3,"10,176.5",147.3,"10,146.1",146.8,"10,101.9",146.2,"10,241.5",148.2,"10,563.5",152.9,"10,374.9",150.1,369.1,5.3,Average

In [8]:
df_Jul[['Size', 'Book Value Per Shr Tangble','Common Shares Outstdg','MktVal Co','Momentum']] = df_Jul[['Size', 'Book Value Per Shr Tangble','Common Shares Outstdg','MktVal Co','Momentum']].astype('float')
df_Jul.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,30 MktVal Co,30 Closing Price,31 MktVal Co,31 Closing Price,STD MktVal,STD Closing Price,ESG_Index
A,"Agilent Technologies, Inc.",NYSE,Healthcare,27286.7,0.5,309.7,26461.7,0.0,17.5,9.3,"5,223.0",10.0,5.5,6.6,AAA,"27,206.4",88.1,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,576.9",89.3,"27,546.0",89.2,"27,647.9",89.5,"27,765.3",89.9,"27,610.9",89.4,"27,610.9",89.4,"27,610.9",89.4,"27,561.5",89.3,"28,003.0",90.7,"28,679.2",92.9,"28,673.1",92.9,"29,139.3",94.4,"29,139.3",94.4,"29,139.3",94.4,"29,398.7",95.2,"29,648.8",96.0,"29,750.7",96.4,"29,846.4",96.7,"29,275.2",94.8,"29,275.2",94.8,"29,275.2",94.8,"30,034.8",97.3,"29,426.5",95.3,"29,982.3",97.1,"29,621.0",95.9,"29,744.5",96.3,997.5,3.2,Leader
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,6641.0,-14.7,428.2,12280.8,-0.5,-59.3,-13.2,"33,361.0",3.3,5.1,2.5,CCC,"6,508.9",12.8,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,503.8",12.8,"6,051.6",11.9,"6,092.2",12.0,"5,680.7",11.2,"6,066.8",11.9,"6,066.8",11.9,"6,066.8",11.9,"5,909.3",11.6,"5,878.8",11.6,"6,829.0",13.4,"6,326.0",12.5,"6,051.6",11.9,"6,051.6",11.9,"6,051.6",11.9,"5,828.0",11.5,"5,828.0",11.5,"5,772.1",11.4,"5,985.8",11.8,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,985.8",11.8,"5,797.6",11.4,"5,685.7",11.2,"5,655.2",11.1,285.7,0.6,Laggard
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3067.7,12.1,66.7,3835.1,0.2,-27.6,15.2,"4,098.8",3.4,6.0,4.8,A,"3,060.3",45.3,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,043.4",45.0,"2,936.0",43.5,"2,961.0",43.8,"2,960.3",43.8,"2,979.9",44.1,"2,979.9",44.1,"2,979.9",44.1,"2,865.7",42.4,"2,894.1",42.8,"3,034.0",44.9,"2,975.9",44.0,"2,915.0",43.1,"2,915.0",43.1,"2,915.0",43.1,"2,879.2",42.6,"2,952.2",43.7,"2,983.1",44.4,"3,017.3",44.9,"3,001.2",44.7,"3,001.2",44.7,"3,001.2",44.7,"3,086.5",46.0,"3,032.7",45.2,"3,651.8",54.4,"3,542.3",52.8,"3,503.4",52.2,184.7,2.8,Average
AAON,"AAON, Inc.",NASDAQ,Industrials,2824.8,5.5,52.1,2574.2,0.1,9.9,12.5,499.2,5.5,7.0,8.4,A,"2,741.5",52.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,840.4",54.6,"2,872.7",55.2,"2,823.8",54.3,"2,780.6",53.4,"2,819.1",54.2,"2,819.1",54.2,"2,819.1",54.2,"2,834.2",54.5,"2,926.3",56.2,"3,000.1",57.7,"2,999.1",57.6,"3,023.0",58.1,"3,023.0",58.1,"3,023.0",58.1,"2,992.3",57.5,"3,012.6",57.9,"3,023.6",58.1,"3,043.3",58.5,"2,999.1",57.6,"2,999.1",57.6,"2,999.1",57.6,"3,013.7",57.9,"2,967.9",57.0,"3,075.1",59.1,"3,030.3",58.2,"3,082.9",59.3,107.1,2.1,Average
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9843.5,26.7,69.2,11092.6,0.2,-8.6,5.8,"9,624.0",2.0,5.9,4.6,BBB,"9,808.9",142.0,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,602.3",139.0,"9,444.8",136.7,"9,428.9",136.5,"9,242.3",133.8,"9,290.7",134.5,"9,290.7",134.5,"9,290.7",134.5,"9,337.6",135.1,"9,576.0",138.6,"9,928.5",143.7,"10,043.9",145.4,"10,010.0",144.9,"10,010.0",144.9,"10,010.0",144.9,"10,012.8",144.9,"10,184.1",147.4,"10,323.7",149.4,"10,252.6",148.4,"10,176.5",147.3,"10,176.5",147.3,"10,176.5",147.3,"10,146.1",146.8,"10,101.9",146.2,"10,241.5",148.2,"10,563.5",152.9,"10,374.9",150.1,369.1,5.3,Average

In [9]:
### Generate the new variable:BM_Ratio
df_Jul['BM_Ratio'] = df_Jul['Book Value Per Shr Tangble']*df_Jul['Common Shares Outstdg']/df_Jul['MktVal Co']
df_Jul.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,30 MktVal Co,30 Closing Price,31 MktVal Co,31 Closing Price,STD MktVal,STD Closing Price,ESG_Index,BM_Ratio
A,"Agilent Technologies, Inc.",NYSE,Healthcare,27286.7,0.5,309.7,26461.7,0.0,17.5,9.3,"5,223.0",10.0,5.5,6.6,AAA,"27,206.4",88.1,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,576.9",89.3,"27,546.0",89.2,"27,647.9",89.5,"27,765.3",89.9,"27,610.9",89.4,"27,610.9",89.4,"27,610.9",89.4,"27,561.5",89.3,"28,003.0",90.7,"28,679.2",92.9,"28,673.1",92.9,"29,139.3",94.4,"29,139.3",94.4,"29,139.3",94.4,"29,398.7",95.2,"29,648.8",96.0,"29,750.7",96.4,"29,846.4",96.7,"29,275.2",94.8,"29,275.2",94.8,"29,275.2",94.8,"30,034.8",97.3,"29,426.5",95.3,"29,982.3",97.1,"29,621.0",95.9,"29,744.5",96.3,997.5,3.2,Leader,0.005852
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,6641.0,-14.7,428.2,12280.8,-0.5,-59.3,-13.2,"33,361.0",3.3,5.1,2.5,CCC,"6,508.9",12.8,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,503.8",12.8,"6,051.6",11.9,"6,092.2",12.0,"5,680.7",11.2,"6,066.8",11.9,"6,066.8",11.9,"6,066.8",11.9,"5,909.3",11.6,"5,878.8",11.6,"6,829.0",13.4,"6,326.0",12.5,"6,051.6",11.9,"6,051.6",11.9,"6,051.6",11.9,"5,828.0",11.5,"5,828.0",11.5,"5,772.1",11.4,"5,985.8",11.8,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,985.8",11.8,"5,797.6",11.4,"5,685.7",11.2,"5,655.2",11.1,285.7,0.6,Laggard,-0.512551
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3067.7,12.1,66.7,3835.1,0.2,-27.6,15.2,"4,098.8",3.4,6.0,4.8,A,"3,060.3",45.3,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,043.4",45.0,"2,936.0",43.5,"2,961.0",43.8,"2,960.3",43.8,"2,979.9",44.1,"2,979.9",44.1,"2,979.9",44.1,"2,865.7",42.4,"2,894.1",42.8,"3,034.0",44.9,"2,975.9",44.0,"2,915.0",43.1,"2,915.0",43.1,"2,915.0",43.1,"2,879.2",42.6,"2,952.2",43.7,"2,983.1",44.4,"3,017.3",44.9,"3,001.2",44.7,"3,001.2",44.7,"3,001.2",44.7,"3,086.5",46.0,"3,032.7",45.2,"3,651.8",54.4,"3,542.3",52.8,"3,503.4",52.2,184.7,2.8,Average,0.210443
AAON,"AAON, Inc.",NASDAQ,Industrials,2824.8,5.5,52.1,2574.2,0.1,9.9,12.5,499.2,5.5,7.0,8.4,A,"2,741.5",52.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,840.4",54.6,"2,872.7",55.2,"2,823.8",54.3,"2,780.6",53.4,"2,819.1",54.2,"2,819.1",54.2,"2,819.1",54.2,"2,834.2",54.5,"2,926.3",56.2,"3,000.1",57.7,"2,999.1",57.6,"3,023.0",58.1,"3,023.0",58.1,"3,023.0",58.1,"2,992.3",57.5,"3,012.6",57.9,"3,023.6",58.1,"3,043.3",58.5,"2,999.1",57.6,"2,999.1",57.6,"2,999.1",57.6,"3,013.7",57.9,"2,967.9",57.0,"3,075.1",59.1,"3,030.3",58.2,"3,082.9",59.3,107.1,2.1,Average,0.111316
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9843.5,26.7,69.2,11092.6,0.2,-8.6,5.8,"9,624.0",2.0,5.9,4.6,BBB,"9,808.9",142.0,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,602.3",139.0,"9,444.8",136.7,"9,428.9",136.5,"9,242.3",133.8,"9,290.7",134.5,"9,290.7",134.5,"9,290.7",134.5,"9,337.6",135.1,"9,576.0",138.6,"9,928.5",143.7,"10,043.9",145.4,"10,010.0",144.9,"10,010.0",144.9,"10,010.0",144.9,"10,012.8",144.9,"10,184.1",147.4,"10,323.7",149.4,"10,252.6",148.4,"10,176.5",147.3,"10,176.5",147.3,"10,176.5",147.3,"10,146.1",146.8,"10,101.9",146.2,"10,241.5",148.2,"10,563.5",152.9,"10,374.9",150.1,369.1,5.3,Average,0.166565

In [10]:
df_Jul.count()

Name                                   1435
Stock Exchange                         1435
Company Main Business                  1435
Size                                   1435
Book Value Per Shr Tangble             1435
Common Shares Outstdg                  1435
MktVal Co                              1435
Book to Market Ratio                   1435
Momentum                               1435
Monthly Return                         1435
Sales                                  1435
MSCI ESG Rtg Score Environmental       1435
MSCI ESG Rtg Score Governance          1435
MSCI ESG Rtg Score Social              1435
MSCI ESG Rtg Overall Company Rating    1435
1 MktVal Co                            1435
1 Closing Price                        1435
2 MktVal Co                            1435
2 Closing Price                        1435
3 MktVal Co                            1435
3 Closing Price                        1435
4 MktVal Co                            1435
4 Closing Price                        1435
5 MktVal Co                            1435
5 Closing Price                        1435
6 MktVal Co                            1435
6 Closing Price                        1435
7 MktVal Co                            1435
7 Closing Price                        1435
8 MktVal Co                            1435
8 Closing Price                        1435
9 MktVal Co                            1435
9 Closing Price                        1435
10 MktVal Co                           1435
10 Closing Price                       1435
11 MktVal Co                           1435
11 Closing Price                       1435
12 MktVal Co                           1435
12 Closing Price                       1435
13 MktVal Co                           1435
13 Closing Price                       1435
14 MktVal Co                           1435
14 Closing Price                       1435
15 MktVal Co                           1435
15 Closing Price                       1435
16 MktVal Co                           1435
16 Closing Price                       1435
17 MktVal Co                           1435
17 Closing Price                       1435
18 MktVal Co                           1435
18 Closing Price                       1435
19 MktVal Co                           1435
19 Closing Price                       1435
20 MktVal Co                           1435
20 Closing Price                       1435
21 MktVal Co                           1435
21 Closing Price                       1435
22 MktVal Co                           1435
22 Closing Price                       1435
23 MktVal Co                           1435
23 Closing Price                       1435
24 MktVal Co                           1435
24 Closing Price                       1435
25 MktVal Co                           1435
25 Closing Price                       1435
26 MktVal Co                           1435
26 Closing Price                       1435
27 MktVal Co                           1435
27 Closing Price                       1435
28 MktVal Co                           1435
28 Closing Price                       1435
29 MktVal Co                           1435
29 Closing Price                       1435
30 MktVal Co                           1435
30 Closing Price                       1435
31 MktVal Co                           1435
31 Closing Price                       1435
STD MktVal                             1435
STD Closing Price                      1435
ESG_Index                              1435
BM_Ratio                               1435
dtype: int64

In [11]:
### Generate the categories by quintile cut of size
df_Jul['Size_Index']=pd.qcut(df_Jul['Size'],5,labels=np.arange(1,6,1))
df_Jul.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,30 MktVal Co,30 Closing Price,31 MktVal Co,31 Closing Price,STD MktVal,STD Closing Price,ESG_Index,BM_Ratio,Size_Index
A,"Agilent Technologies, Inc.",NYSE,Healthcare,27286.7,0.5,309.7,26461.7,0.0,17.5,9.3,"5,223.0",10.0,5.5,6.6,AAA,"27,206.4",88.1,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,382.4",88.7,"27,576.9",89.3,"27,546.0",89.2,"27,647.9",89.5,"27,765.3",89.9,"27,610.9",89.4,"27,610.9",89.4,"27,610.9",89.4,"27,561.5",89.3,"28,003.0",90.7,"28,679.2",92.9,"28,673.1",92.9,"29,139.3",94.4,"29,139.3",94.4,"29,139.3",94.4,"29,398.7",95.2,"29,648.8",96.0,"29,750.7",96.4,"29,846.4",96.7,"29,275.2",94.8,"29,275.2",94.8,"29,275.2",94.8,"30,034.8",97.3,"29,426.5",95.3,"29,982.3",97.1,"29,621.0",95.9,"29,744.5",96.3,997.5,3.2,Leader,0.005852,5
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,6641.0,-14.7,428.2,12280.8,-0.5,-59.3,-13.2,"33,361.0",3.3,5.1,2.5,CCC,"6,508.9",12.8,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,351.4",12.5,"6,503.8",12.8,"6,051.6",11.9,"6,092.2",12.0,"5,680.7",11.2,"6,066.8",11.9,"6,066.8",11.9,"6,066.8",11.9,"5,909.3",11.6,"5,878.8",11.6,"6,829.0",13.4,"6,326.0",12.5,"6,051.6",11.9,"6,051.6",11.9,"6,051.6",11.9,"5,828.0",11.5,"5,828.0",11.5,"5,772.1",11.4,"5,985.8",11.8,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,792.5",11.4,"5,985.8",11.8,"5,797.6",11.4,"5,685.7",11.2,"5,655.2",11.1,285.7,0.6,Laggard,-0.512551,4
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3067.7,12.1,66.7,3835.1,0.2,-27.6,15.2,"4,098.8",3.4,6.0,4.8,A,"3,060.3",45.3,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,022.5",44.7,"3,043.4",45.0,"2,936.0",43.5,"2,961.0",43.8,"2,960.3",43.8,"2,979.9",44.1,"2,979.9",44.1,"2,979.9",44.1,"2,865.7",42.4,"2,894.1",42.8,"3,034.0",44.9,"2,975.9",44.0,"2,915.0",43.1,"2,915.0",43.1,"2,915.0",43.1,"2,879.2",42.6,"2,952.2",43.7,"2,983.1",44.4,"3,017.3",44.9,"3,001.2",44.7,"3,001.2",44.7,"3,001.2",44.7,"3,086.5",46.0,"3,032.7",45.2,"3,651.8",54.4,"3,542.3",52.8,"3,503.4",52.2,184.7,2.8,Average,0.210443,3
AAON,"AAON, Inc.",NASDAQ,Industrials,2824.8,5.5,52.1,2574.2,0.1,9.9,12.5,499.2,5.5,7.0,8.4,A,"2,741.5",52.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,795.7",53.7,"2,840.4",54.6,"2,872.7",55.2,"2,823.8",54.3,"2,780.6",53.4,"2,819.1",54.2,"2,819.1",54.2,"2,819.1",54.2,"2,834.2",54.5,"2,926.3",56.2,"3,000.1",57.7,"2,999.1",57.6,"3,023.0",58.1,"3,023.0",58.1,"3,023.0",58.1,"2,992.3",57.5,"3,012.6",57.9,"3,023.6",58.1,"3,043.3",58.5,"2,999.1",57.6,"2,999.1",57.6,"2,999.1",57.6,"3,013.7",57.9,"2,967.9",57.0,"3,075.1",59.1,"3,030.3",58.2,"3,082.9",59.3,107.1,2.1,Average,0.111316,3
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9843.5,26.7,69.2,11092.6,0.2,-8.6,5.8,"9,624.0",2.0,5.9,4.6,BBB,"9,808.9",142.0,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,801.3",141.8,"9,602.3",139.0,"9,444.8",136.7,"9,428.9",136.5,"9,242.3",133.8,"9,290.7",134.5,"9,290.7",134.5,"9,290.7",134.5,"9,337.6",135.1,"9,576.0",138.6,"9,928.5",143.7,"10,043.9",145.4,"10,010.0",144.9,"10,010.0",144.9,"10,010.0",144.9,"10,012.8",144.9,"10,184.1",147.4,"10,323.7",149.4,"10,252.6",148.4,"10,176.5",147.3,"10,176.5",147.3,"10,176.5",147.3,"10,146.1",146.8,"10,101.9",146.2,"10,241.5",148.2,"10,563.5",152.9,"10,374.9",150.1,369.1,5.3,Average,0.166565,4

In [12]:
df_Jul.groupby('Size_Index').size()

Size_Index
1    287
2    287
3    287
4    287
5    287
dtype: int64

In [13]:
### generate the categories further by quintile of BM Ratio within each Size group. 
df_Jul['BM_Ratio_Index'] = df_Jul.groupby(['Size_Index'])['BM_Ratio'].transform(
                     lambda x: pd.qcut(x, 5, labels=np.arange(1,6,1)))

In [14]:
df_Jul.groupby(by=['Size_Index','BM_Ratio_Index']).size()

Size_Index  BM_Ratio_Index
1           1.0               58
            2.0               57
            3.0               57
            4.0               57
            5.0               58
2           1.0               58
            2.0               57
            3.0               57
            4.0               57
            5.0               58
3           1.0               58
            2.0               57
            3.0               57
            4.0               57
            5.0               58
4           1.0               58
            2.0               57
            3.0               57
            4.0               57
            5.0               58
5           1.0               58
            2.0               57
            3.0               57
            4.0               57
            5.0               58
dtype: int64

In [15]:
### generate the categories further by quintile of Momentum within each previous group
df_Jul['Momentum_Index'] = df_Jul.groupby(by=['Size_Index','BM_Ratio_Index'])['Momentum'].transform(
                     lambda x: pd.qcut(x, 5, labels=np.arange(1,6,1)))

In [16]:
df_Jul.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index']).size()

Size_Index  BM_Ratio_Index  Momentum_Index
1           1.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            4.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
2           1.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               12
                            3.0               10
                            4.0               11
                            5.0               12
            4.0             1.0               12
                            2.0               12
                            3.0               10
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
3           1.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            4.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
4           1.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            4.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               13
                            4.0               10
                            5.0               12
5           1.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            4.0             1.0               13
                            2.0               10
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
dtype: int64

In [17]:
df_Jul_Overview=df_Jul[['Size_Index','BM_Ratio_Index','Momentum_Index','ESG_Index','Monthly Return']]
df_Jul_Overview.head()

     Size_Index  BM_Ratio_Index  Momentum_Index ESG_Index  Monthly Return
A             5             3.0             4.0    Leader             9.3
AAL           4             1.0             1.0   Laggard           -13.2
AAN           3             3.0             1.0   Average            15.2
AAON          3             3.0             4.0   Average            12.5
AAP           4             4.0             3.0   Average             5.8

In [18]:
df_Jul_Overview.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).size()

    Size_Index  BM_Ratio_Index  Momentum_Index  size
0            1             1.0             1.0    12
1            1             1.0             2.0    11
2            1             1.0             3.0    12
3            1             1.0             4.0    11
4            1             1.0             5.0    12
5            1             2.0             1.0    12
6            1             2.0             2.0    11
7            1             2.0             3.0    11
8            1             2.0             4.0    11
9            1             2.0             5.0    12
10           1             3.0             1.0    12
11           1             3.0             2.0    11
12           1             3.0             3.0    11
13           1             3.0             4.0    11
14           1             3.0             5.0    12
15           1             4.0             1.0    12
16           1             4.0             2.0    11
17           1             4.0             3.0    11
18           1             4.0             4.0    11
19           1             4.0             5.0    12
20           1             5.0             1.0    12
21           1             5.0             2.0    11
22           1             5.0             3.0    12
23           1             5.0             4.0    11
24           1             5.0             5.0    12
25           2             1.0             1.0    12
26           2             1.0             2.0    11
27           2             1.0             3.0    12
28           2             1.0             4.0    11
29           2             1.0             5.0    12
30           2             2.0             1.0    12
31           2             2.0             2.0    11
32           2             2.0             3.0    11
33           2             2.0             4.0    11
34           2             2.0             5.0    12
35           2             3.0             1.0    12
36           2             3.0             2.0    12
37           2             3.0             3.0    10
38           2             3.0             4.0    11
39           2             3.0             5.0    12
40           2             4.0             1.0    12
41           2             4.0             2.0    12
42           2             4.0             3.0    10
43           2             4.0             4.0    11
44           2             4.0             5.0    12
45           2             5.0             1.0    12
46           2             5.0             2.0    11
47           2             5.0             3.0    12
48           2             5.0             4.0    11
49           2             5.0             5.0    12
50           3             1.0             1.0    12
51           3             1.0             2.0    11
52           3             1.0             3.0    12
53           3             1.0             4.0    11
54           3             1.0             5.0    12
55           3             2.0             1.0    12
56           3             2.0             2.0    11
57           3             2.0             3.0    11
58           3             2.0             4.0    11
59           3             2.0             5.0    12
60           3             3.0             1.0    12
61           3             3.0             2.0    11
62           3             3.0             3.0    11
63           3             3.0             4.0    11
64           3             3.0             5.0    12
65           3             4.0             1.0    12
66           3             4.0             2.0    11
67           3             4.0             3.0    11
68           3             4.0             4.0    11
69           3             4.0             5.0    12
70           3             5.0             1.0    12
71           3             5.0             2.0    11
72           3             5.0             3.0    12
73           3             5.0             4.0    11
74           3             5.0             5.0    12
75           4             1.0             1.0    12
76           4             1.0             2.0    11
77           4             1.0             3.0    12
78           4             1.0             4.0    11
79           4             1.0             5.0    12
80           4             2.0             1.0    12
81           4             2.0             2.0    11
82           4             2.0             3.0    11
83           4             2.0             4.0    11
84           4             2.0             5.0    12
85           4             3.0             1.0    12
86           4             3.0             2.0    11
87           4             3.0             3.0    11
88           4             3.0             4.0    11
89           4             3.0             5.0    12
90           4             4.0             1.0    12
91           4             4.0             2.0    11
92           4             4.0             3.0    11
93           4             4.0             4.0    11
94           4             4.0             5.0    12
95           4             5.0             1.0    12
96           4             5.0             2.0    11
97           4             5.0             3.0    13
98           4             5.0             4.0    10
99           4             5.0             5.0    12
100          5             1.0             1.0    12
101          5             1.0             2.0    11
102          5             1.0             3.0    12
103          5             1.0             4.0    11
104          5             1.0             5.0    12
105          5             2.0             1.0    12
106          5             2.0             2.0    11
107          5             2.0             3.0    11
108          5             2.0             4.0    11
109          5             2.0             5.0    12
110          5             3.0             1.0    12
111          5             3.0             2.0    11
112          5             3.0             3.0    11
113          5             3.0             4.0    11
114          5             3.0             5.0    12
115          5             4.0             1.0    13
116          5             4.0             2.0    10
117          5             4.0             3.0    11
118          5             4.0             4.0    11
119          5             4.0             5.0    12
120          5             5.0             1.0    12
121          5             5.0             2.0    11
122          5             5.0             3.0    12
123          5             5.0             4.0    11
124          5             5.0             5.0    12

In [19]:
df_Jul_Overview_Benchmark = df_Jul_Overview.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).mean('Monthly Return')

In [20]:
df_Jul_Overview_Benchmark.head()

  Size_Index  BM_Ratio_Index  Momentum_Index  Monthly Return
0          1             1.0             1.0        3.133333
1          1             1.0             2.0        9.763636
2          1             1.0             3.0       11.933333
3          1             1.0             4.0        8.854545
4          1             1.0             5.0       23.150000

In [21]:
df_Jul_Overview_Leader = df_Jul_Overview[df_Jul_Overview['ESG_Index']=='Leader']
df_Jul_Overview_Laggard = df_Jul_Overview[df_Jul_Overview['ESG_Index']=='Laggard']
df_Jul_Overview_Average = df_Jul_Overview[df_Jul_Overview['ESG_Index']=='Average']
df_Jul_Overview_Leader.head()

     Size_Index  BM_Ratio_Index  Momentum_Index ESG_Index  Monthly Return
A             5             3.0             4.0    Leader             9.3
ACIW          3             1.0             2.0    Leader            -0.8
ACM           4             2.0             3.0    Leader            -0.3
ACN           5             3.0             3.0    Leader             5.1
ADBE          5             3.0             5.0    Leader             1.0

In [22]:
df_Jul_Overveiw_Leader_Mean = df_Jul_Overview_Leader.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).mean('Monthly Return')
df_Jul_Overveiw_Laggard_Mean = df_Jul_Overview_Laggard.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).mean('Monthly Return')
df_Jul_Overveiw_Average_Mean = df_Jul_Overview_Average.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).mean('Monthly Return')
df_Jul_Overveiw_Leader_Mean.head()

  Size_Index  BM_Ratio_Index  Momentum_Index  Monthly Return
0          1             1.0             1.0            7.15
1          1             1.0             2.0           27.40
2          1             1.0             3.0           16.80
3          1             1.0             4.0           17.30
4          1             1.0             5.0          112.70

In [23]:
df_Jul_Overview_Benchmark['Leader Monthly Return']= df_Jul_Overveiw_Leader_Mean['Monthly Return']
df_Jul_Overview_Benchmark['Laggard Monthly Return']= df_Jul_Overveiw_Laggard_Mean['Monthly Return']
df_Jul_Overview_Benchmark['Average Monthly Return']= df_Jul_Overveiw_Average_Mean['Monthly Return']
df_Jul_Overview_Benchmark.head()

,Size_Index,BM_Ratio_Index,Momentum_Index,Monthly Return,Leader Monthly Return,Laggard Monthly Return,Average Monthly Return
0,1,1.0,1.0,3.133333,7.15,0.666667,3.042857
1,1,1.0,2.0,9.763636,27.40,3.850000,6.414286
2,1,1.0,3.0,11.933333,16.80,NaN,11.490909
3,1,1.0,4.0,8.854545,17.30,5.350000,8.675000
4,1,1.0,5.0,23.150000,112.70,28.775000,7.142857

In [24]:
df_Jul_Overview_Benchmark['Leader Abnormal Return']=df_Jul_Overview_Benchmark['Leader Monthly Return']-df_Jul_Overview_Benchmark['Monthly Return']
df_Jul_Overview_Benchmark['Laggard Abnormal Return']=df_Jul_Overview_Benchmark['Laggard Monthly Return']-df_Jul_Overview_Benchmark['Monthly Return']
df_Jul_Overview_Benchmark['Average Abnormal Return']=df_Jul_Overview_Benchmark['Average Monthly Return']-df_Jul_Overview_Benchmark['Monthly Return']
df_Jul_Overview_Benchmark.head()

,Size_Index,BM_Ratio_Index,Momentum_Index,Monthly Return,Leader Monthly Return,Laggard Monthly Return,Average Monthly Return,Leader Abnormal Return,Laggard Abnormal Return,Average Abnormal Return
0,1,1.0,1.0,3.133333,7.15,0.666667,3.042857,4.016667,-2.466667,-0.090476
1,1,1.0,2.0,9.763636,27.40,3.850000,6.414286,17.636364,-5.913636,-3.349351
2,1,1.0,3.0,11.933333,16.80,NaN,11.490909,4.866667,NaN,-0.442424
3,1,1.0,4.0,8.854545,17.30,5.350000,8.675000,8.445455,-3.504545,-0.179545
4,1,1.0,5.0,23.150000,112.70,28.775000,7.142857,89.550000,5.625000,-16.007143

In [25]:
###unpivot the table
df_Jul_AR = df_Jul_Overview_Benchmark.melt(id_vars=['Size_Index', 'BM_Ratio_Index',	'Momentum_Index'], value_vars=['Leader Abnormal Return', 'Laggard Abnormal Return','Average Abnormal Return'],var_name='ESG Rating', value_name='Abnormal Return')
df_Jul_AR=df_Jul_AR.dropna()
df_Jul_AR.head()

,Size_Index,BM_Ratio_Index,Momentum_Index,ESG Rating,Abnormal Return
0,1,1.0,1.0,Leader Abnormal Return,4.016667
1,1,1.0,2.0,Leader Abnormal Return,17.636364
2,1,1.0,3.0,Leader Abnormal Return,4.866667
3,1,1.0,4.0,Leader Abnormal Return,8.445455
4,1,1.0,5.0,Leader Abnormal Return,89.550000

In [26]:
df_Jul_AR['ESG Rating']=df_Jul_AR['ESG Rating'].apply(lambda x:'Leader' if x=='Leader Abnormal Return' else 'Laggard' if x=='Laggard Abnormal Return' else 'Average' )
df_Jul_AR.head()

  Size_Index  BM_Ratio_Index  Momentum_Index ESG Rating  Abnormal Return
0          1             1.0             1.0     Leader         4.016667
1          1             1.0             2.0     Leader        17.636364
2          1             1.0             3.0     Leader         4.866667
3          1             1.0             4.0     Leader         8.445455
4          1             1.0             5.0     Leader        89.550000

In [27]:
df_Jul_AR['Month']='Jul'
df_Jul_AR.head()

  Size_Index  BM_Ratio_Index  Momentum_Index ESG Rating  Abnormal Return Month
0          1             1.0             1.0     Leader         4.016667   Jul
1          1             1.0             2.0     Leader        17.636364   Jul
2          1             1.0             3.0     Leader         4.866667   Jul
3          1             1.0             4.0     Leader         8.445455   Jul
4          1             1.0             5.0     Leader        89.550000   Jul

In [28]:
import plotly.express as px

In [29]:
fig = px.box(df_Jul_AR, y="Abnormal Return", x='ESG Rating'
                   )
fig.show()

In [30]:
df_Jul_AR.to_csv('Jul_AR.csv')