<a href="https://colab.research.google.com/github/sunshineluyao/ESG_with_benchmark/blob/main/Categorization/ESG_Categorization_Feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### import packages
import pandas as pd
import numpy as np
### show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
### Import data
df_Feb= pd.read_csv("https://raw.githubusercontent.com/sunshineluyao/ESG_with_benchmark/main/rawdata/SP1500_Feb.csv")
df_Feb.head()

,Symbol,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
0,A,"Agilent Technologies, Inc.",NYSE,Healthcare,"25,608.7",0.5,309.7,"26,461.7",0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
1,AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"11,492.9",-14.7,428.2,"12,280.8",-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
2,AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,986.1",12.1,66.7,"3,835.1",0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
3,AAOI,"Applied Optoelectronics, Inc.",NASDAQ,Technology,227.4,13.4,20.1,239.0,1.1,-34.6,-21.0,200.4,NaN,NaN,NaN,@NA,227.4,11.3,227.4,11.3,233.8,11.6,249.5,12.4,244.1,12.1,233.0,11.6,226.8,11.3,226.8,11.3,226.8,11.3,227.4,11.3,231.6,11.5,250.7,12.5,256.5,12.8,239.4,11.9,239.4,11.9,239.4,11.9,239.4,11.9,236.4,11.8,243.0,12.1,237.8,11.8,227.0,11.3,227.0,11.3,227.0,11.3,213.0,10.6,205.1,10.2,204.8,10.2,192.3,9.6,179.7,8.9,179.7,8.9,19.1,1.0
4,AAON,"AAON, Inc.",NASDAQ,Industrials,"2,732.0",5.5,52.1,"2,574.2",0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5

In [3]:
df_Feb=df_Feb.dropna()

In [4]:
df_Feb=df_Feb.set_index('Symbol',drop=True)
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
Symbol,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
A,"Agilent Technologies, Inc.",NYSE,Healthcare,"25,608.7",0.5,309.7,"26,461.7",0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"11,492.9",-14.7,428.2,"12,280.8",-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,986.1",12.1,66.7,"3,835.1",0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
AAON,"AAON, Inc.",NASDAQ,Industrials,"2,732.0",5.5,52.1,"2,574.2",0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,"9,124.9",26.7,69.2,"11,092.6",0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5

In [5]:
df_Feb.index.name=None
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
A,"Agilent Technologies, Inc.",NYSE,Healthcare,"25,608.7",0.5,309.7,"26,461.7",0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"11,492.9",-14.7,428.2,"12,280.8",-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,986.1",12.1,66.7,"3,835.1",0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
AAON,"AAON, Inc.",NASDAQ,Industrials,"2,732.0",5.5,52.1,"2,574.2",0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,"9,124.9",26.7,69.2,"11,092.6",0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5

In [6]:
### formating data so that it can be calculated
df_Feb[['Size','Common Shares Outstdg','MktVal Co']]=df_Feb[['Size','Common Shares Outstdg','MktVal Co']].apply(lambda x: x.str.replace(',', ''), axis=1)
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5

In [7]:
df_Feb[['Size', 'Book Value Per Shr Tangble','Common Shares Outstdg','MktVal Co','Momentum']] = df_Feb[['Size', 'Book Value Per Shr Tangble','Common Shares Outstdg','MktVal Co','Momentum']].astype('float')
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5

In [8]:
### Generate the new variable:BM_Ratio
df_Feb['BM_Ratio'] = df_Feb['Book Value Per Shr Tangble']*df_Feb['Common Shares Outstdg']/df_Feb['MktVal Co']
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price,BM_Ratio
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9,0.005852
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2,-0.512551
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5,0.210443
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5,0.111316
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5,0.166565

In [9]:
### Generate the categories by quintile cut and ESG rating
df_Feb['Size_Index']=pd.qcut(df_Feb['Size'],5,labels=np.arange(1,6,1))
df_Feb['Momentum_Index']=pd.qcut(df_Feb['Momentum'],5,labels=np.arange(1,6,1))
df_Feb['BM_Ratio_Index']=pd.qcut(df_Feb['BM_Ratio'],5,labels=np.arange(1,6,1))
df_Feb['ESG_Index']=np.where(df_Feb['MSCI ESG Rtg Overall Company Rating'].isin(['A','AA','AAA']), 'High','Low')
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price,BM_Ratio,Size_Index,Momentum_Index,BM_Ratio_Index,ESG_Index
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9,0.005852,5,3,2,High
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2,-0.512551,4,1,1,Low
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5,0.210443,3,4,3,High
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5,0.111316,2,5,3,High
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5,0.166565,4,1,3,Low

In [11]:
df_Feb_Overview=df_Feb[['Size_Index','Momentum_Index','BM_Ratio_Index','ESG_Index','Monthly Return']]

In [12]:
df_Feb_Overview_Benchmark = df_Feb_Overview.groupby(by=['Size_Index','Momentum_Index','BM_Ratio_Index',],group_keys=True,sort=True,as_index=False).mean('Monthly Return')

In [13]:
df_Feb_Overview_Benchmark.head()

  Size_Index Momentum_Index BM_Ratio_Index  Monthly Return
0          1              1              1       -5.329167
1          1              1              2       -7.116667
2          1              1              3       -0.061905
3          1              1              4      -12.005882
4          1              1              5      -10.073333

In [15]:
df_Feb_Overview_ESG_High = df_Feb_Overview[df_Feb_Overview['ESG_Index']=='High']
df_Feb_Overview_ESG_High.head()

     Size_Index Momentum_Index BM_Ratio_Index ESG_Index  Monthly Return
A             5              3              2      High            -6.6
AAN           3              4              3      High           -33.7
AAON          2              5              3      High             4.9
AAPL          5              5              2      High           -11.4
AAXN          3              5              3      High             0.7

In [16]:
df_Feb_Overveiw_ESG_High_Mean = df_Feb_Overview_ESG_High.groupby(by=['Size_Index','Momentum_Index','BM_Ratio_Index',],group_keys=True,sort=True,as_index=False).mean('Monthly Return')

In [17]:
df_Feb_Overveiw_ESG_High_Mean.head()

  Size_Index Momentum_Index BM_Ratio_Index  Monthly Return
0          1              1              1            0.60
1          1              1              2            0.55
2          1              1              3          -10.00
3          1              1              4          -12.85
4          1              1              5          -11.74

In [18]:
df_Feb_Overview_Benchmark['ESG_High_Return']= df_Feb_Overveiw_ESG_High_Mean['Monthly Return']
df_Feb_Overview_Benchmark.head()

  Size_Index Momentum_Index BM_Ratio_Index  Monthly Return  ESG_High_Return
0          1              1              1       -5.329167             0.60
1          1              1              2       -7.116667             0.55
2          1              1              3       -0.061905           -10.00
3          1              1              4      -12.005882           -12.85
4          1              1              5      -10.073333           -11.74

In [19]:
df_Feb_Overview_Benchmark['Abnormal Return']=df_Feb_Overview_Benchmark['ESG_High_Return']-df_Feb_Overview_Benchmark['Monthly Return']
df_Feb_Overview_Benchmark.head()

,Size_Index,Momentum_Index,BM_Ratio_Index,Monthly Return,ESG_High_Return,Abnormal Return
0,1,1,1,-5.329167,0.60,5.929167
1,1,1,2,-7.116667,0.55,7.666667
2,1,1,3,-0.061905,-10.00,-9.938095
3,1,1,4,-12.005882,-12.85,-0.844118
4,1,1,5,-10.073333,-11.74,-1.666667

In [20]:
df_Feb_Overview_Benchmark['Month']='Feb'
df_Feb_Overview_Benchmark.head()

,Size_Index,Momentum_Index,BM_Ratio_Index,Monthly Return,ESG_High_Return,Abnormal Return,Month
0,1,1,1,-5.329167,0.60,5.929167,Feb
1,1,1,2,-7.116667,0.55,7.666667,Feb
2,1,1,3,-0.061905,-10.00,-9.938095,Feb
3,1,1,4,-12.005882,-12.85,-0.844118,Feb
4,1,1,5,-10.073333,-11.74,-1.666667,Feb

In [21]:
import plotly.express as px

In [23]:
fig = px.box(df_Feb_Overview_Benchmark, y="Abnormal Return",
                   hover_data=df_Feb_Overview_Benchmark.columns)
fig.show()

/usr/local/lib/python3.6/dist-packages/plotly/express/_core.py:286: FutureWarning:

Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.

/usr/local/lib/python3.6/dist-packages/plotly/express/_core.py:283: FutureWarning:

Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.

In [24]:
df_Feb_Overview_Benchmark.to_csv('Overview_Feb.csv')