<a href="https://colab.research.google.com/github/sunshineluyao/ESG_with_benchmark/blob/main/Categorization/ESG_Categorization_Feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### import packages
import pandas as pd
import numpy as np
### show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
### Import data
df_Feb= pd.read_csv("https://raw.githubusercontent.com/sunshineluyao/ESG_with_benchmark/main/rawdata/SP1500_Feb.csv")
df_Feb.head()

,Symbol,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
0,A,"Agilent Technologies, Inc.",NYSE,Healthcare,"25,608.7",0.5,309.7,"26,461.7",0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
1,AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"11,492.9",-14.7,428.2,"12,280.8",-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
2,AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,986.1",12.1,66.7,"3,835.1",0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
3,AAOI,"Applied Optoelectronics, Inc.",NASDAQ,Technology,227.4,13.4,20.1,239.0,1.1,-34.6,-21.0,200.4,NaN,NaN,NaN,@NA,227.4,11.3,227.4,11.3,233.8,11.6,249.5,12.4,244.1,12.1,233.0,11.6,226.8,11.3,226.8,11.3,226.8,11.3,227.4,11.3,231.6,11.5,250.7,12.5,256.5,12.8,239.4,11.9,239.4,11.9,239.4,11.9,239.4,11.9,236.4,11.8,243.0,12.1,237.8,11.8,227.0,11.3,227.0,11.3,227.0,11.3,213.0,10.6,205.1,10.2,204.8,10.2,192.3,9.6,179.7,8.9,179.7,8.9,19.1,1.0
4,AAON,"AAON, Inc.",NASDAQ,Industrials,"2,732.0",5.5,52.1,"2,574.2",0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5

In [3]:
df_Feb=df_Feb.dropna()

In [4]:
df_Feb=df_Feb.set_index('Symbol',drop=True)
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
Symbol,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
A,"Agilent Technologies, Inc.",NYSE,Healthcare,"25,608.7",0.5,309.7,"26,461.7",0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"11,492.9",-14.7,428.2,"12,280.8",-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,986.1",12.1,66.7,"3,835.1",0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
AAON,"AAON, Inc.",NASDAQ,Industrials,"2,732.0",5.5,52.1,"2,574.2",0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,"9,124.9",26.7,69.2,"11,092.6",0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5

In [5]:
df_Feb.index.name=None
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
A,"Agilent Technologies, Inc.",NYSE,Healthcare,"25,608.7",0.5,309.7,"26,461.7",0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,"11,492.9",-14.7,428.2,"12,280.8",-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,"3,986.1",12.1,66.7,"3,835.1",0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
AAON,"AAON, Inc.",NASDAQ,Industrials,"2,732.0",5.5,52.1,"2,574.2",0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,"9,124.9",26.7,69.2,"11,092.6",0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5

In [6]:
### formating data so that it can be calculated
df_Feb[['Size','Common Shares Outstdg','MktVal Co']]=df_Feb[['Size','Common Shares Outstdg','MktVal Co']].apply(lambda x: x.str.replace(',', ''), axis=1)
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5

In [7]:
Conds=[
       df_Feb['MSCI ESG Rtg Overall Company Rating'].isin(['AAA','AA']),
       df_Feb['MSCI ESG Rtg Overall Company Rating'].isin(['CCC','B']),
       df_Feb['MSCI ESG Rtg Overall Company Rating'].isin(['BB','BBB','A'])
]
Choices = [
           'Leader',
           'Laggard',
           'Average'
]
df_Feb['ESG_Index'] =np.select(Conds, Choices)
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price,ESG_Index
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9,Leader
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2,Laggard
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5,Average
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5,Average
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5,Average

In [8]:
df_Feb[['Size', 'Book Value Per Shr Tangble','Common Shares Outstdg','MktVal Co','Momentum']] = df_Feb[['Size', 'Book Value Per Shr Tangble','Common Shares Outstdg','MktVal Co','Momentum']].astype('float')
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price,ESG_Index
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9,Leader
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2,Laggard
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5,Average
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5,Average
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5,Average

In [9]:
### Generate the new variable:BM_Ratio
df_Feb['BM_Ratio'] = df_Feb['Book Value Per Shr Tangble']*df_Feb['Common Shares Outstdg']/df_Feb['MktVal Co']
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price,ESG_Index,BM_Ratio
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9,Leader,0.005852
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2,Laggard,-0.512551
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5,Average,0.210443
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5,Average,0.111316
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5,Average,0.166565

In [10]:
df_Feb.count()

Name                                   1426
Stock Exchange                         1426
Company Main Business                  1426
Size                                   1426
Book Value Per Shr Tangble             1426
Common Shares Outstdg                  1426
MktVal Co                              1426
Book to Market Ratio                   1426
Momentum                               1426
Monthly Return                         1426
Sales                                  1426
MSCI ESG Rtg Score Environmental       1426
MSCI ESG Rtg Score Governance          1426
MSCI ESG Rtg Score Social              1426
MSCI ESG Rtg Overall Company Rating    1426
1 MktVal Co                            1426
1 Closing Price                        1426
2 MktVal Co                            1426
2 Closing Price                        1426
3 MktVal Co                            1426
3 Closing Price                        1426
4 MktVal Co                            1426
4 Closing Price                        1426
5 MktVal Co                            1426
5 Closing Price                        1426
6 MktVal Co                            1426
6 Closing Price                        1426
7 MktVal Co                            1426
7 Closing Price                        1426
8 MktVal Co                            1426
8 Closing Price                        1426
9 MktVal Co                            1426
9 Closing Price                        1426
10 MktVal Co                           1426
10 Closing Price                       1426
11 MktVal Co                           1426
11 Closing Price                       1426
12 MktVal Co                           1426
12 Closing Price                       1426
13 MktVal Co                           1426
13 Closing Price                       1426
14 MktVal Co                           1426
14 Closing Price                       1426
15 MktVal Co                           1426
15 Closing Price                       1426
16 MktVal Co                           1426
16 Closing Price                       1426
17 MktVal Co                           1426
17 Closing Price                       1426
18 MktVal Co                           1426
18 Closing Price                       1426
19 MktVal Co                           1426
19 Closing Price                       1426
20 MktVal Co                           1426
20 Closing Price                       1426
21 MktVal Co                           1426
21 Closing Price                       1426
22 MktVal Co                           1426
22 Closing Price                       1426
23 MktVal Co                           1426
23 Closing Price                       1426
24 MktVal Co                           1426
24 Closing Price                       1426
25 MktVal Co                           1426
25 Closing Price                       1426
26 MktVal Co                           1426
26 Closing Price                       1426
27 MktVal Co                           1426
27 Closing Price                       1426
28 MktVal Co                           1426
28 Closing Price                       1426
29 MktVal Co                           1426
29 Closing Price                       1426
STD MktVal                             1426
STD Closing Price                      1426
ESG_Index                              1426
BM_Ratio                               1426
dtype: int64

In [11]:
### Generate the categories by quintile cut of size
df_Feb['Size_Index']=pd.qcut(df_Feb['Size'],5,labels=np.arange(1,6,1))
df_Feb.head()

,Name,Stock Exchange,Company Main Business,Size,Book Value Per Shr Tangble,Common Shares Outstdg,MktVal Co,Book to Market Ratio,Momentum,Monthly Return,Sales,MSCI ESG Rtg Score Environmental,MSCI ESG Rtg Score Governance,MSCI ESG Rtg Score Social,MSCI ESG Rtg Overall Company Rating,1 MktVal Co,1 Closing Price,2 MktVal Co,2 Closing Price,3 MktVal Co,3 Closing Price,4 MktVal Co,4 Closing Price,5 MktVal Co,5 Closing Price,6 MktVal Co,6 Closing Price,7 MktVal Co,7 Closing Price,8 MktVal Co,8 Closing Price,9 MktVal Co,9 Closing Price,10 MktVal Co,10 Closing Price,11 MktVal Co,11 Closing Price,12 MktVal Co,12 Closing Price,13 MktVal Co,13 Closing Price,14 MktVal Co,14 Closing Price,15 MktVal Co,15 Closing Price,16 MktVal Co,16 Closing Price,17 MktVal Co,17 Closing Price,18 MktVal Co,18 Closing Price,19 MktVal Co,19 Closing Price,20 MktVal Co,20 Closing Price,21 MktVal Co,21 Closing Price,22 MktVal Co,22 Closing Price,23 MktVal Co,23 Closing Price,24 MktVal Co,24 Closing Price,25 MktVal Co,25 Closing Price,26 MktVal Co,26 Closing Price,27 MktVal Co,27 Closing Price,28 MktVal Co,28 Closing Price,29 MktVal Co,29 Closing Price,STD MktVal,STD Closing Price,ESG_Index,BM_Ratio,Size_Index
A,"Agilent Technologies, Inc.",NYSE,Healthcare,25608.7,0.5,309.7,26461.7,0.0,9.5,-6.6,"5,223.0",10.0,5.5,6.6,AAA,"25,608.7",82.6,"25,608.7",82.6,"25,481.5",82.2,"25,906.5",83.5,"26,343.8",84.9,"26,309.7",84.8,"25,797.9",83.2,"25,797.9",83.2,"25,797.9",83.2,"26,188.8",84.4,"26,443.3",85.1,"26,548.9",85.4,"26,561.3",85.5,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,670.1",85.8,"26,350.0",84.8,"26,524.1",85.4,"26,210.2",84.3,"26,437.0",85.1,"26,437.0",85.1,"26,437.0",85.1,"25,016.8",80.5,"24,224.4",78.0,"24,274.1",78.1,"24,062.8",77.4,"23,950.9",77.1,"23,950.9",77.1,905.3,2.9,Leader,0.005852,5
AAL,"American Airlines Group, Inc.",NASDAQ,Industrials,11492.9,-14.7,428.2,12280.8,-0.5,-24.6,-28.7,"33,361.0",3.3,5.1,2.5,CCC,"11,492.9",26.8,"11,492.9",26.8,"11,629.9",27.2,"12,173.7",28.4,"12,460.6",29.1,"12,118.1",28.3,"12,152.3",28.4,"12,152.3",28.4,"12,152.3",28.4,"12,327.9",28.8,"12,777.5",29.8,"13,047.3",30.5,"12,884.5",30.1,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,440.9",29.2,"12,198.1",28.6,"12,070.2",28.3,"12,146.9",28.5,"11,853.0",27.8,"11,853.0",27.8,"11,853.0",27.8,"10,843.2",25.5,"9,850.5",23.1,"9,505.4",22.3,"8,776.8",20.6,"8,116.4",19.1,"8,116.4",19.1,"1,363.9",3.2,Laggard,-0.512551,4
AAN,"Aaron's, Inc.",NYSE,Consumer Cyclicals,3986.1,12.1,66.7,3835.1,0.2,19.5,-33.7,"4,098.8",3.4,6.0,4.8,A,"3,986.1",59.4,"3,986.1",59.4,"4,054.0",60.4,"3,706.8",55.2,"3,799.5",56.6,"3,823.0",56.9,"3,726.9",55.5,"3,726.9",55.5,"3,726.9",55.5,"3,808.2",56.7,"3,931.8",58.6,"3,886.1",57.9,"3,916.3",58.3,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,908.2",58.2,"3,864.6",57.6,"3,770.6",56.2,"3,052.1",45.5,"2,892.1",43.3,"2,892.1",43.3,"2,892.1",43.3,"2,888.7",43.3,"2,850.0",42.7,"2,769.9",41.5,"2,733.2",41.0,"2,625.1",39.3,"2,625.1",39.3,514.3,7.5,Average,0.210443,3
AAON,"AAON, Inc.",NASDAQ,Industrials,2732.0,5.5,52.1,2574.2,0.1,44.4,4.9,499.2,5.5,7.0,8.4,A,"2,732.0",52.4,"2,732.0",52.4,"2,765.4",53.1,"2,782.0",53.4,"2,818.5",54.1,"2,832.0",54.4,"2,839.3",54.5,"2,839.3",54.5,"2,839.3",54.5,"2,858.4",54.9,"2,871.1",55.1,"2,900.3",55.7,"2,936.2",56.4,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,973.8",57.1,"2,903.9",55.7,"2,976.9",57.1,"2,943.0",56.5,"2,878.2",55.2,"2,878.2",55.2,"2,878.2",55.2,"2,800.8",53.8,"2,762.2",53.0,"2,767.4",53.1,"3,000.3",57.6,"2,865.6",55.0,"2,865.6",55.0,78.8,1.5,Average,0.111316,2
AAP,"Advance Auto Parts, Inc.",NYSE,Consumer Cyclicals,9124.9,26.7,69.2,11092.6,0.2,-17.0,0.9,"9,624.0",2.0,5.9,4.6,BBB,"9,124.9",131.8,"9,124.9",131.8,"9,187.3",132.7,"9,111.8",131.6,"9,489.9",137.0,"9,306.4",134.4,"9,206.7",132.9,"9,206.7",132.9,"9,206.7",132.9,"9,050.8",130.7,"9,149.9",132.1,"9,302.9",134.3,"9,327.2",134.7,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,252.4",133.6,"9,821.7",141.8,"9,704.6",140.1,"9,868.1",142.5,"9,738.6",140.6,"9,738.6",140.6,"9,738.6",140.6,"9,690.1",139.9,"9,530.1",137.6,"9,318.2",134.5,"9,289.8",134.1,"9,210.1",133.0,"9,210.1",133.0,245.7,3.5,Average,0.166565,4

In [12]:
df_Feb.groupby('Size_Index').size()

Size_Index
1    286
2    285
3    285
4    285
5    285
dtype: int64

In [13]:
### generate the categories further by quintile of BM Ratio within each Size group. 
df_Feb['BM_Ratio_Index'] = df_Feb.groupby(['Size_Index'])['BM_Ratio'].transform(
                     lambda x: pd.qcut(x, 5, labels=np.arange(1,6,1)))

In [14]:
df_Feb.groupby(by=['Size_Index','BM_Ratio_Index']).size()

Size_Index  BM_Ratio_Index
1           1.0               58
            2.0               57
            3.0               57
            4.0               57
            5.0               57
2           1.0               57
            2.0               57
            3.0               57
            4.0               57
            5.0               57
3           1.0               57
            2.0               57
            3.0               57
            4.0               57
            5.0               57
4           1.0               57
            2.0               57
            3.0               57
            4.0               57
            5.0               57
5           1.0               57
            2.0               57
            3.0               57
            4.0               57
            5.0               57
dtype: int64

In [15]:
### generate the categories further by quintile of Momentum within each previous group
df_Feb['Momentum_Index'] = df_Feb.groupby(by=['Size_Index','BM_Ratio_Index'])['Momentum'].transform(
                     lambda x: pd.qcut(x, 5, labels=np.arange(1,6,1)))

In [16]:
df_Feb.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index']).size()

Size_Index  BM_Ratio_Index  Momentum_Index
1           1.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            4.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
2           1.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               12
                            4.0               10
                            5.0               12
            4.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
3           1.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            4.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
4           1.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            4.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
5           1.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               12
                            5.0               11
            2.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            3.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            4.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
            5.0             1.0               12
                            2.0               11
                            3.0               11
                            4.0               11
                            5.0               12
dtype: int64

In [17]:
df_Feb_Overview=df_Feb[['Size_Index','BM_Ratio_Index','Momentum_Index','ESG_Index','Monthly Return']]
df_Feb_Overview.head()

     Size_Index  BM_Ratio_Index  Momentum_Index ESG_Index  Monthly Return
A             5             3.0             2.0    Leader            -6.6
AAL           4             1.0             1.0   Laggard           -28.7
AAN           3             3.0             3.0   Average           -33.7
AAON          2             2.0             5.0   Average             4.9
AAP           4             4.0             1.0   Average             0.9

In [18]:
df_Feb_Overview.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).size()

    Size_Index  BM_Ratio_Index  Momentum_Index  size
0            1             1.0             1.0    12
1            1             1.0             2.0    11
2            1             1.0             3.0    12
3            1             1.0             4.0    11
4            1             1.0             5.0    12
5            1             2.0             1.0    12
6            1             2.0             2.0    11
7            1             2.0             3.0    11
8            1             2.0             4.0    11
9            1             2.0             5.0    12
10           1             3.0             1.0    12
11           1             3.0             2.0    11
12           1             3.0             3.0    11
13           1             3.0             4.0    11
14           1             3.0             5.0    12
15           1             4.0             1.0    12
16           1             4.0             2.0    11
17           1             4.0             3.0    11
18           1             4.0             4.0    11
19           1             4.0             5.0    12
20           1             5.0             1.0    12
21           1             5.0             2.0    11
22           1             5.0             3.0    11
23           1             5.0             4.0    11
24           1             5.0             5.0    12
25           2             1.0             1.0    12
26           2             1.0             2.0    11
27           2             1.0             3.0    11
28           2             1.0             4.0    11
29           2             1.0             5.0    12
30           2             2.0             1.0    12
31           2             2.0             2.0    11
32           2             2.0             3.0    11
33           2             2.0             4.0    11
34           2             2.0             5.0    12
35           2             3.0             1.0    12
36           2             3.0             2.0    11
37           2             3.0             3.0    12
38           2             3.0             4.0    10
39           2             3.0             5.0    12
40           2             4.0             1.0    12
41           2             4.0             2.0    11
42           2             4.0             3.0    11
43           2             4.0             4.0    11
44           2             4.0             5.0    12
45           2             5.0             1.0    12
46           2             5.0             2.0    11
47           2             5.0             3.0    11
48           2             5.0             4.0    11
49           2             5.0             5.0    12
50           3             1.0             1.0    12
51           3             1.0             2.0    11
52           3             1.0             3.0    11
53           3             1.0             4.0    11
54           3             1.0             5.0    12
55           3             2.0             1.0    12
56           3             2.0             2.0    11
57           3             2.0             3.0    11
58           3             2.0             4.0    11
59           3             2.0             5.0    12
60           3             3.0             1.0    12
61           3             3.0             2.0    11
62           3             3.0             3.0    11
63           3             3.0             4.0    11
64           3             3.0             5.0    12
65           3             4.0             1.0    12
66           3             4.0             2.0    11
67           3             4.0             3.0    11
68           3             4.0             4.0    11
69           3             4.0             5.0    12
70           3             5.0             1.0    12
71           3             5.0             2.0    11
72           3             5.0             3.0    11
73           3             5.0             4.0    11
74           3             5.0             5.0    12
75           4             1.0             1.0    12
76           4             1.0             2.0    11
77           4             1.0             3.0    11
78           4             1.0             4.0    11
79           4             1.0             5.0    12
80           4             2.0             1.0    12
81           4             2.0             2.0    11
82           4             2.0             3.0    11
83           4             2.0             4.0    11
84           4             2.0             5.0    12
85           4             3.0             1.0    12
86           4             3.0             2.0    11
87           4             3.0             3.0    11
88           4             3.0             4.0    11
89           4             3.0             5.0    12
90           4             4.0             1.0    12
91           4             4.0             2.0    11
92           4             4.0             3.0    11
93           4             4.0             4.0    11
94           4             4.0             5.0    12
95           4             5.0             1.0    12
96           4             5.0             2.0    11
97           4             5.0             3.0    11
98           4             5.0             4.0    11
99           4             5.0             5.0    12
100          5             1.0             1.0    12
101          5             1.0             2.0    11
102          5             1.0             3.0    11
103          5             1.0             4.0    12
104          5             1.0             5.0    11
105          5             2.0             1.0    12
106          5             2.0             2.0    11
107          5             2.0             3.0    11
108          5             2.0             4.0    11
109          5             2.0             5.0    12
110          5             3.0             1.0    12
111          5             3.0             2.0    11
112          5             3.0             3.0    11
113          5             3.0             4.0    11
114          5             3.0             5.0    12
115          5             4.0             1.0    12
116          5             4.0             2.0    11
117          5             4.0             3.0    11
118          5             4.0             4.0    11
119          5             4.0             5.0    12
120          5             5.0             1.0    12
121          5             5.0             2.0    11
122          5             5.0             3.0    11
123          5             5.0             4.0    11
124          5             5.0             5.0    12

In [19]:
df_Feb_Overview_Benchmark = df_Feb_Overview.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).mean('Monthly Return')

In [20]:
df_Feb_Overview_Benchmark.head()

  Size_Index  BM_Ratio_Index  Momentum_Index  Monthly Return
0          1             1.0             1.0       -4.516667
1          1             1.0             2.0       -6.709091
2          1             1.0             3.0      -12.275000
3          1             1.0             4.0       -4.845455
4          1             1.0             5.0      -10.475000

In [21]:
df_Feb_Overview_Leader = df_Feb_Overview[df_Feb_Overview['ESG_Index']=='Leader']
df_Feb_Overview_Laggard = df_Feb_Overview[df_Feb_Overview['ESG_Index']=='Laggard']
df_Feb_Overview_Average = df_Feb_Overview[df_Feb_Overview['ESG_Index']=='Average']
df_Feb_Overview_Leader.head()

     Size_Index  BM_Ratio_Index  Momentum_Index ESG_Index  Monthly Return
A             5             3.0             2.0    Leader            -6.6
ACIW          3             1.0             3.0    Leader           -19.1
ACM           4             2.0             5.0    Leader            -6.8
ACN           5             3.0             4.0    Leader           -12.0
ADBE          5             2.0             5.0    Leader            -1.7

In [22]:
df_Feb_Overveiw_Leader_Mean = df_Feb_Overview_Leader.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).mean('Monthly Return')
df_Feb_Overveiw_Laggard_Mean = df_Feb_Overview_Laggard.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).mean('Monthly Return')
df_Feb_Overveiw_Average_Mean = df_Feb_Overview_Average.groupby(by=['Size_Index','BM_Ratio_Index','Momentum_Index'],group_keys=True,sort=True,as_index=False).mean('Monthly Return')
df_Feb_Overveiw_Leader_Mean.head()

  Size_Index  BM_Ratio_Index  Momentum_Index  Monthly Return
0          1             1.0             1.0             NaN
1          1             1.0             2.0       -4.800000
2          1             1.0             3.0      -17.733333
3          1             1.0             4.0      -20.800000
4          1             1.0             5.0             NaN

In [23]:
df_Feb_Overview_Benchmark['Leader Monthly Return']= df_Feb_Overveiw_Leader_Mean['Monthly Return']
df_Feb_Overview_Benchmark['Laggard Monthly Return']= df_Feb_Overveiw_Laggard_Mean['Monthly Return']
df_Feb_Overview_Benchmark['Average Monthly Return']= df_Feb_Overveiw_Average_Mean['Monthly Return']
df_Feb_Overview_Benchmark.head()

,Size_Index,BM_Ratio_Index,Momentum_Index,Monthly Return,Leader Monthly Return,Laggard Monthly Return,Average Monthly Return
0,1,1.0,1.0,-4.516667,NaN,-23.00,-2.836364
1,1,1.0,2.0,-6.709091,-4.800000,18.55,-13.262500
2,1,1.0,3.0,-12.275000,-17.733333,-3.30,-11.350000
3,1,1.0,4.0,-4.845455,-20.800000,0.80,-4.985714
4,1,1.0,5.0,-10.475000,NaN,-2.25,-14.587500

In [24]:
df_Feb_Overview_Benchmark['Leader Abnormal Return']=df_Feb_Overview_Benchmark['Leader Monthly Return']-df_Feb_Overview_Benchmark['Monthly Return']
df_Feb_Overview_Benchmark['Laggard Abnormal Return']=df_Feb_Overview_Benchmark['Laggard Monthly Return']-df_Feb_Overview_Benchmark['Monthly Return']
df_Feb_Overview_Benchmark['Average Abnormal Return']=df_Feb_Overview_Benchmark['Average Monthly Return']-df_Feb_Overview_Benchmark['Monthly Return']
df_Feb_Overview_Benchmark.head()

,Size_Index,BM_Ratio_Index,Momentum_Index,Monthly Return,Leader Monthly Return,Laggard Monthly Return,Average Monthly Return,Leader Abnormal Return,Laggard Abnormal Return,Average Abnormal Return
0,1,1.0,1.0,-4.516667,NaN,-23.00,-2.836364,NaN,-18.483333,1.680303
1,1,1.0,2.0,-6.709091,-4.800000,18.55,-13.262500,1.909091,25.259091,-6.553409
2,1,1.0,3.0,-12.275000,-17.733333,-3.30,-11.350000,-5.458333,8.975000,0.925000
3,1,1.0,4.0,-4.845455,-20.800000,0.80,-4.985714,-15.954545,5.645455,-0.140260
4,1,1.0,5.0,-10.475000,NaN,-2.25,-14.587500,NaN,8.225000,-4.112500

In [25]:
###unpivot the table
df_Feb_AR = df_Feb_Overview_Benchmark.melt(id_vars=['Size_Index', 'BM_Ratio_Index',	'Momentum_Index'], value_vars=['Leader Abnormal Return', 'Laggard Abnormal Return','Average Abnormal Return'],var_name='ESG Rating', value_name='Abnormal Return')
df_Feb_AR=df_Feb_AR.dropna()
df_Feb_AR.head()

,Size_Index,BM_Ratio_Index,Momentum_Index,ESG Rating,Abnormal Return
1,1,1.0,2.0,Leader Abnormal Return,1.909091
2,1,1.0,3.0,Leader Abnormal Return,-5.458333
3,1,1.0,4.0,Leader Abnormal Return,-15.954545
6,1,2.0,2.0,Leader Abnormal Return,1.945455
9,1,2.0,5.0,Leader Abnormal Return,-1.658333

In [26]:
df_Feb_AR['ESG Rating']=df_Feb_AR['ESG Rating'].apply(lambda x:'Leader' if x=='Leader Abnormal Return' else 'Laggard' if x=='Laggard Abnormal Return' else 'Average' )
df_Feb_AR.head()

  Size_Index  BM_Ratio_Index  Momentum_Index ESG Rating  Abnormal Return
1          1             1.0             2.0     Leader         1.909091
2          1             1.0             3.0     Leader        -5.458333
3          1             1.0             4.0     Leader       -15.954545
6          1             2.0             2.0     Leader         1.945455
9          1             2.0             5.0     Leader        -1.658333

In [27]:
df_Feb_AR['Month']='Feb'
df_Feb_AR.head()

  Size_Index  BM_Ratio_Index  Momentum_Index ESG Rating  Abnormal Return Month
1          1             1.0             2.0     Leader         1.909091   Feb
2          1             1.0             3.0     Leader        -5.458333   Feb
3          1             1.0             4.0     Leader       -15.954545   Feb
6          1             2.0             2.0     Leader         1.945455   Feb
9          1             2.0             5.0     Leader        -1.658333   Feb

In [28]:
import plotly.express as px

In [29]:
fig = px.box(df_Feb_AR, y="Abnormal Return", x='ESG Rating'
                   )
fig.show()

In [30]:
df_Feb_AR.to_csv('Feb_AR.csv')